CREATE TABLE `user` (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,    username VARCHAR (45) UNIQUE                          NOT NULL,    password VARCHAR (45) NOT NULL, points INT DEFAULT (0));
CREATE TABLE category(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, name VARCHAR (45) UNIQUE NOT NULL);
CREATE TABLE question ( id INTEGER PRIMARY KEY NOT NULL, category INTEGER NOT NULL, wright INTEGER NOT NULL, value VARCHAR (45) NOT NULL, response1 VARCHAR (45) NOT NULL, response2 VARCHAR (45) NOT NULL, response3 VARCHAR (45) NOT NULL, response4 VARCHAR (45) NOT NULL, additional_data VARCHAR (45), win_points INTEGER DEFAULT (0), FOREIGN KEY(category) REFERENCES category(id));
INSERT INTO category values(1, "Film & Serie");
INSERT INTO category values(2, "Cultura generale");
INSERT INTO category values(3, "Musica");
INSERT INTO category values(4, "Programmazione");
INSERT INTO question values(null, 4, 3, "Qual è il concetto, in programmazione OOP, che permette di comporre le classi in una gerarchia?", "Polimorfismo", "Type-Inference", "Ereditarietà", "Covarianza", null, 10);
INSERT INTO question values(null, 4, 3, "Quale funzione, in Kotlin, ti permette di creare una mappa mutabile con oggetti di tipo T?", "mapOf<T>()", "mutableMapOf<T>()", "Map.of<T>()", "Collections.mapOf<T>()", null, 30);
INSERT INTO question values(null, 4, 4, "Qual è il framework di Android che permette il supporto delle sue librerie legacy?", "Spring", "Android Studio", "androidx", "Android Jetpack", null, 40);
INSERT INTO question values(null, 4, 1, "Senza di cosa è impossibile creare un'app android (che non sia un widget)?", "Activity", "Fragment", "Navigator", "Kotlin", null, 20);
INSERT INTO question values(null, 4, 2, "Qual è il l'RDBMS standard usato per gestire la persistenza in android?", "MySQLite", "SQLite", "LiteMySQL", "MongoLiteDb", null, 10);
INSERT INTO question values(null, 4, 1, "Quale software (in primo piano) permette in modo semplice la gestione dei cosiddetti 'container' virtuali e garantisce la compatibilità con quasi tutti i progetti software?", "Docker", "Kotlin", "Java Virtual Machine", "Spring Security", null, 20);
INSERT INTO question values(null, 4, 2, "Quale tipo di file, in Java, ti permette di gestire il comportamento di una classe con il vincolo di lasciarti creare solo proprietà statiche e metodi astratti?", "Classi Generiche", "Interfacce", "Classi Astratte", "Data class", null, 30);
INSERT INTO question values(null, 4, 2, "Che cosa, nella programmazione, è considerato memory leak?", "Puntare ad un indirizzo di memoria di un altro servizio", "Quando non si dealloca la memoria", "Quando si chiamano dei metodi in loop", "Quando le classi non vengono implementate correttamente", null, 30);
INSERT INTO question values(null, 4, 1, "Quale di questi algoritmi è spiegato nel video?", "Insertion sort", "Merge sort", "Selection sort", "Switch sort", "insertion", 30);
INSERT INTO question values(null, 4, 2, "Quale di questi algoritmi è spiegato nel video?", "Apple sort", "Min sort", "Bubble sort", "Hexagon sort", "bubble", 30);
INSERT INTO question values(null, 4, 2, "Quale di questi algoritmi è spiegato nel video?", "Merge sort", "Linear search", "Quick sort", "Binary search", "quick", 30);
INSERT INTO question values(null, 3, 2, "Quale musicista ha composto 'La Valchiria'", "Wolfgang Amadeus Mozart", "Richard Wagner", "Robert C. Martin", "Ludwig van Beethoven", null, 30);
INSERT INTO question values(null, 3, 4, "Come si intitola l'opera di Chopin famosissima nel film 'Il Pianista'?", "Nocturne Op. 9, No. 1", "Swan Lake", "Für Elise", "Nocturne in C# minor", null, 30);
INSERT INTO question values(null, 1, 2, "Come s'intitola il film di Woody Allen dove il protagonista s'identifica con qualunque persona con cui interagisce?", "Crimini e Misfatti", "Zelig", "Match Point", "Arancia meccanica", null, 30);
INSERT INTO question values(null, 1, 3, "Qual è il nome della serie TV più famosa sulle distopie digitali?", "Z Nation", "The Barrier", "Black Mirror", "Scary Movie", null, 30);
INSERT INTO question values(null, 2, 4, "Qual è circa il tempo che la luce ci mette a percorrere dal Sole alla Terra?", "Circa 0 secondi", "1 minuto", "10 ore", "8 minuti", null, 30);
INSERT INTO question values(null, 2, 3, "Chi, pur avendo una sola voce, si trasforma in quadrupede, bipede e tripede?", "Il verme del Nicaragua", "La sfinge", "L'uomo", "Il serpente a sonagli", null, 30);